name: 'Deploy to NuxtHub'
description: 'Deploy your Nuxt application to NuxtHub'
author: 'NuxtHub'

branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  project-key:
    description: 'The project key of the NuxtHub project to deploy to.'
    required: false
  directory:
    description: 'The root directory of your Nuxt application to be used as the working directory for the build step.'
    required: false
    default: ''
  output-directory:
    description: 'The output directory containing the built Nuxt application to deploy, relative to the directory specified in `directory`. Defaults to `dist`.'
    required: false
    default: 'dist'
  hub-url:
    description: 'The base URL of the NuxtHub dashboard.'
    required: false
    default: 'https://admin.hub.nuxt.com'
  build:
    description: 'Set to "true" to build the project before deploying. If "false", the action will skip the build step and deploy the contents of the output directory as-is.'
    required: false
    default: "false"
  build-command:
    description: 'The command to run to build your Nuxt application. Executed in the directory specified in `directory`.'
    required: false
    default: "npm run build"

outputs:
  environment:
    description: 'The environment of the deployment'
  deployment-url:
    description: 'The URL of the deployment - preview environments link to the specific deployment of the commit'
  environment-url:
    description: 'The URL of the environment'
  branch-url:
    description: 'The URL of the deployment branch'

runs:
  using: node20
  main: dist/index.mjs
