name: 'Deploy to NuxtHub'
description: 'Deploy your Nuxt application to NuxtHub'
author: 'NuxtHub'

branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  project-key:
    description: 'The project key of the NuxtHub project to deploy to'
    required: false
  directory:
    description: 'The directory of the built Nuxt application'
    required: false
    default: 'dist'
  hub-url:
    description: 'The URL of the NuxtHub dashboard'
    required: false
    default: 'https://admin.hub.nuxt.com'

outputs:
  environment:
    description: 'The environment of the deployment'
  deployment-url:
    description: 'The URL of the deployment - preview environments link to the specific deployment of the commit'
  branch-url:
    description: 'The URL of the deployment branch'

runs:
  using: node20
  main: dist/index.mjs
